[package]
name = "actor_game"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
rand = "0.8"
wgpu = "0.16"
image = "0.24"
bytemuck = { version = "1.14", features = ["derive"] }
pollster = "0.3"
raw-window-handle = "0.5"

# アセットファイルを含める
[package.metadata]
assets = "assets/"

